export const contractsPackage = "@runxhq/contracts";

export {
  RUNX_SCHEMA_BASE_URL,
  RUNX_CONTRACT_IDS,
  RUNX_LOGICAL_SCHEMAS,
  RUNX_CONTROL_SCHEMA_REFS,
  RUNX_AUXILIARY_SCHEMA_IDS,
} from "./internal.js";

export {
  credentialGrantReferenceSchema,
  credentialEnvelopeSchema,
  scopeAdmissionSchema,
  authorityProofSchema,
  authorityProofSchemaVersion,
  validateCredentialEnvelopeContract,
  validateScopeAdmissionContract,
  validateAuthorityProofContract,
  type CredentialGrantReferenceContract,
  type CredentialEnvelopeContract,
  type ScopeAdmissionContract,
  type AuthorityProofContract,
} from "./schemas/credentials.js";

export {
  outputScalarSchema,
  outputObjectEntrySchema,
  outputEntrySchema,
  outputSchema,
  validateOutputContract,
  type OutputScalarContract,
  type OutputObjectEntryContract,
  type OutputEntryContract,
  type OutputContract,
} from "./schemas/output.js";

export {
  artifactProducerSchema,
  artifactMetaSchema,
  artifactEnvelopeSchema,
  type ArtifactProducerContract,
  type ArtifactMetaContract,
  type ArtifactEnvelopeContract,
} from "./schemas/artifact.js";

export {
  agentContextProvenanceSchema,
  contextDocumentSchema,
  contextSchema,
  qualityProfileContextSchema,
  executionLocationSchema,
  agentContextEnvelopeSchema,
  validateAgentContextEnvelopeContract,
  type AgentContextProvenanceContract,
  type ContextDocumentContract,
  type ContextContract,
  type QualityProfileContextContract,
  type ExecutionLocationContract,
  type AgentContextEnvelopeContract,
} from "./schemas/context.js";

export {
  agentActInvocationSchema,
  questionSchema,
  approvalGateSchema,
  validateAgentActInvocationContract,
  validateQuestionContract,
  validateApprovalGateContract,
  type AgentActInvocationContract,
  type QuestionContract,
  type ApprovalGateContract,
} from "./schemas/agent-act.js";

export {
  inputResolutionRequestSchema,
  approvalResolutionRequestSchema,
  agentActResolutionRequestSchema,
  resolutionRequestSchema,
  resolutionResponseSchema,
  actReceiptTerminalEnvelopeSchema,
  actReceiptNeedsResolutionEnvelopeSchema,
  actReceiptEnvelopeSchema,
  validateResolutionRequestContract,
  validateResolutionResponseContract,
  validateActReceiptEnvelopeContract,
  type InputResolutionRequestContract,
  type ApprovalResolutionRequestContract,
  type AgentActResolutionRequestContract,
  type ResolutionRequestContract,
  type ResolutionResponseContract,
  type ActReceiptEnvelopeContract,
} from "./schemas/resolution.js";

export {
  registryBindingSchema,
  reviewReceiptOutputSchema,
  validateRegistryBindingContract,
  validateReviewReceiptOutputContract,
  type RegistryBindingContract,
  type ReviewReceiptOutputContract,
} from "./schemas/registry.js";

export {
  doctorRepairSchema,
  doctorLocationSchema,
  doctorDiagnosticSchema,
  doctorSummarySchema,
  doctorV1Schema,
  validateDoctorReportContract,
  type DoctorRepairContract,
  type DoctorLocationContract,
  type DoctorDiagnosticContract,
  type DoctorSummaryContract,
  type DoctorReportContract,
} from "./schemas/doctor.js";

export {
  devV1Schema,
  validateDevReportContract,
  type DevFixtureAssertionContract,
  type DevFixtureResultContract,
  type DevReportContract,
} from "./schemas/dev.js";

export {
  runxListRequestedKindSchema,
  runxListItemKindSchema,
  runxListSourceSchema,
  runxListItemSchema,
  listV1Schema,
  validateRunxListReportContract,
  type RunxListRequestedKindContract,
  type RunxListItemKindContract,
  type RunxListSourceContract,
  type RunxListEmitContract,
  type RunxListItemContract,
  type RunxListReportContract,
} from "./schemas/list.js";

export {
  receiptV1Schema,
  type ReceiptContract,
} from "./schemas/receipt.js";

export {
  localReceiptSchema,
  localSkillReceiptSchema,
  localGraphReceiptSchema,
  localReceiptSchemaVersion,
  localReceiptDispositions,
  localOutcomeStates,
  validateLocalReceiptContract,
  validateLocalSkillReceiptContract,
  validateLocalGraphReceiptContract,
  type LocalReceiptContract,
  type LocalSkillReceiptContract,
  type LocalGraphReceiptContract,
} from "./schemas/local-receipt.js";

export {
  outcomeResolutionSchema,
  outcomeResolutionSchemaVersion,
  validateOutcomeResolutionContract,
  type OutcomeResolutionContract,
} from "./schemas/outcome-resolution.js";

export {
  validateArtifactEnvelopeContract,
} from "./schemas/artifact.js";

export {
  ledgerRecordSchemaVersion,
  ledgerChainSchemaVersion,
  ledgerHashAlgorithm,
  ledgerCanonicalization,
  ledgerChainSchema,
  ledgerRecordSchema,
  validateLedgerRecordContract,
  type LedgerChainContract,
  type LedgerRecordContract,
} from "./schemas/ledger.js";

export {
  hostedReceiptManifestSchema,
  hostedReceiptIndexEntrySchema,
  hostedArtifactIndexEntrySchema,
  validateHostedReceiptManifestContract,
  type HostedReceiptManifestContract,
  type HostedReceiptIndexEntryContract,
  type HostedArtifactIndexEntryContract,
} from "./schemas/hosted-receipt-manifest.js";

export {
  fixtureV1Schema,
  type FixtureContract,
} from "./schemas/fixture.js";

export {
  toolManifestV1Schema,
  type ToolManifestContract,
} from "./schemas/tool-manifest.js";

export {
  packetIndexV1Schema,
  type PacketIndexEntryContract,
  type PacketIndexContract,
} from "./schemas/packet-index.js";

export {
  actAssignmentActorSchema,
  actAssignmentHostSchema,
  actAssignmentIdempotencySchema,
  actAssignmentV1Schema,
  validateActAssignmentContract,
  type ActAssignmentActorContract,
  type ActAssignmentHostContract,
  type ActAssignmentIdempotencyContract,
  type ActAssignmentContract,
} from "./schemas/act-assignment.js";

export {
  referenceTypes,
  signalTypes,
  signalTrustLevels,
  harnessStates,
  harnessSealDispositions,
  decisionChoices,
  actForms,
  targetLifecycleStates,
  thesisProofStrengths,
  authorityCostLevels,
  selectionCycleStates,
  criterionStatuses,
  verificationStatuses,
  authorityResourceFamilies,
  authorityVerbs,
  authorityCapabilities,
  authorityConditionPredicates,
  redactionCommitmentAlgorithms,
  referenceTypeSchema,
  signalTypeSchema,
  signalTrustLevelSchema,
  harnessStateSchema,
  harnessSealDispositionSchema,
  decisionChoiceSchema,
  actFormSchema,
  targetLifecycleStateSchema,
  thesisProofStrengthSchema,
  authorityCostLevelSchema,
  selectionCycleStateSchema,
  criterionStatusSchema,
  verificationStatusSchema,
  authorityResourceFamilySchema,
  authorityVerbSchema,
  authorityCapabilitySchema,
  authorityConditionPredicateSchema,
  redactionCommitmentAlgorithmSchema,
  referenceSchema,
  nullableReferenceSchema,
  actReferenceSchema,
  hashCommitmentSchema,
  redactionSchema,
  fingerprintSchema,
  duplicateCandidateSchema,
  linksSchema,
  signalAuthenticitySchema,
  signalSchema,
  authorityBoundsSchema,
  authorityConditionSchema,
  authorityApprovalSchema,
  authorityTermSchema,
  authoritySubsetComparisonSchema,
  authoritySubsetProofSchema,
  harnessAuthorityAttenuationSchema,
  harnessAuthoritySchema,
  successCriterionSchema,
  intentSchema,
  verificationCheckSchema,
  verificationSchema,
  targetSurfaceSchema,
  changeRequestSchema,
  changePlanSchema,
  revisionDetailsSchema,
  verificationDetailsSchema,
  criterionBindingSchema,
  actSchema,
  decisionInputsSchema,
  decisionJustificationSchema,
  closureSchema,
  decisionSchema,
  harnessSandboxSchema,
  harnessEnforcementSchema,
  harnessIdempotencySchema,
  harnessRevisionSchema,
  harnessSealCriterionSchema,
  harnessSealSchema,
  harnessSchema,
  artifactSchema,
  harnessReceiptIssuerSchema,
  harnessReceiptSignatureSchema,
  harnessReceiptEnvelopeSchema,
  harnessReceiptSchema,
  targetCooldownSchema,
  targetSchema,
  opportunitySchema,
  thesisAssessmentSchema,
  selectionSchema,
  skillBindingSchema,
  targetTransitionEntrySchema,
  selectionCycleSchema,
  reflectionEntrySchema,
  feedEntrySchema,
  validateReferenceContract,
  validateSignalContract,
  validateAuthorityContract,
  validateAuthoritySubsetProofContract,
  validateDecisionContract,
  validateActContract,
  validateVerificationContract,
  validateHarnessContract,
  validateHarnessReceiptContract,
  validateSpineArtifactContract,
  validateRedactionContract,
  validateTargetContract,
  validateOpportunityContract,
  validateThesisAssessmentContract,
  validateSelectionContract,
  validateSkillBindingContract,
  validateTargetTransitionEntryContract,
  validateSelectionCycleContract,
  validateReflectionEntryContract,
  validateFeedEntryContract,
  type ReferenceTypeContract,
  type SignalTypeContract,
  type SignalTrustLevelContract,
  type HarnessStateContract,
  type HarnessSealDispositionContract,
  type DecisionChoiceContract,
  type ActFormContract,
  type TargetLifecycleStateContract,
  type ThesisProofStrengthContract,
  type AuthorityCostLevelContract,
  type SelectionCycleStateContract,
  type CriterionStatusContract,
  type VerificationStatusContract,
  type AuthorityResourceFamilyContract,
  type AuthorityVerbContract,
  type AuthorityCapabilityContract,
  type AuthorityConditionPredicateContract,
  type ReferenceContract,
  type ActReferenceContract,
  type HashCommitmentContract,
  type RedactionContract,
  type FingerprintContract,
  type LinksContract,
  type SignalAuthenticityContract,
  type SignalContract,
  type AuthorityBoundsContract,
  type AuthorityConditionContract,
  type AuthorityApprovalContract,
  type AuthorityTermContract,
  type AuthoritySubsetProofContract,
  type HarnessAuthorityContract,
  type SuccessCriterionContract,
  type IntentContract,
  type VerificationCheckContract,
  type VerificationContract,
  type TargetSurfaceContract,
  type ChangeRequestContract,
  type ChangePlanContract,
  type RevisionDetailsContract,
  type VerificationDetailsContract,
  type CriterionBindingContract,
  type ActContract,
  type DecisionInputsContract,
  type DecisionJustificationContract,
  type ClosureRecordContract,
  type DecisionContract,
  type HarnessSandboxContract,
  type HarnessEnforcementContract,
  type HarnessIdempotencyContract,
  type HarnessRevisionContract,
  type HarnessSealCriterionContract,
  type HarnessSealContract,
  type HarnessContract,
  type ArtifactContract,
  type HarnessReceiptIssuerContract,
  type HarnessReceiptSignatureContract,
  type HarnessReceiptContract,
  type HarnessReceiptEnvelopeContract,
  type TargetCooldownContract,
  type TargetContract,
  type OpportunityContract,
  type ThesisAssessmentContract,
  type SelectionContract,
  type SkillBindingContract,
  type TargetTransitionEntryContract,
  type SelectionCycleContract,
  type ReflectionEntryContract,
  type FeedEntryContract,
} from "./schemas/spine.js";

export {
  handoffSignalV1Schema,
  handoffStateV1Schema,
  suppressionRecordV1Schema,
  validateHandoffSignalContract,
  validateHandoffStateContract,
  validateSuppressionRecordContract,
  type HandoffSignalContract,
  type HandoffStateContract,
  type SuppressionRecordContract,
} from "./schemas/handoff.js";

import { agentContextEnvelopeSchema } from "./schemas/context.js";
import { agentActInvocationSchema, approvalGateSchema, questionSchema } from "./schemas/agent-act.js";
import { credentialEnvelopeSchema, scopeAdmissionSchema, authorityProofSchema } from "./schemas/credentials.js";
import { outputSchema } from "./schemas/output.js";
import { actReceiptEnvelopeSchema, resolutionRequestSchema, resolutionResponseSchema } from "./schemas/resolution.js";
import { registryBindingSchema, reviewReceiptOutputSchema } from "./schemas/registry.js";
import { doctorV1Schema } from "./schemas/doctor.js";
import { devV1Schema } from "./schemas/dev.js";
import { listV1Schema } from "./schemas/list.js";
import { receiptV1Schema } from "./schemas/receipt.js";
import { fixtureV1Schema } from "./schemas/fixture.js";
import { toolManifestV1Schema } from "./schemas/tool-manifest.js";
import { packetIndexV1Schema } from "./schemas/packet-index.js";
import { actAssignmentV1Schema } from "./schemas/act-assignment.js";
import {
  actSchema,
  artifactSchema,
  authoritySubsetProofSchema,
  decisionSchema,
  harnessAuthoritySchema,
  harnessReceiptSchema,
  harnessSchema,
  targetSchema,
  opportunitySchema,
  thesisAssessmentSchema,
  selectionSchema,
  skillBindingSchema,
  targetTransitionEntrySchema,
  selectionCycleSchema,
  reflectionEntrySchema,
  feedEntrySchema,
  redactionSchema,
  referenceSchema,
  signalSchema,
  verificationSchema,
} from "./schemas/spine.js";
import { ledgerRecordSchema } from "./schemas/ledger.js";
import { handoffSignalV1Schema, handoffStateV1Schema, suppressionRecordV1Schema } from "./schemas/handoff.js";

export const runxContractSchemas = {
  output: outputSchema,
  agentContextEnvelope: agentContextEnvelopeSchema,
  agentActInvocation: agentActInvocationSchema,
  question: questionSchema,
  approvalGate: approvalGateSchema,
  resolutionRequest: resolutionRequestSchema,
  resolutionResponse: resolutionResponseSchema,
  actReceiptEnvelope: actReceiptEnvelopeSchema,
  credentialEnvelope: credentialEnvelopeSchema,
  scopeAdmission: scopeAdmissionSchema,
  authorityProof: authorityProofSchema,
  doctor: doctorV1Schema,
  dev: devV1Schema,
  list: listV1Schema,
  receipt: receiptV1Schema,
  fixture: fixtureV1Schema,
  toolManifest: toolManifestV1Schema,
  packetIndex: packetIndexV1Schema,
  actAssignment: actAssignmentV1Schema,
  reference: referenceSchema,
  authority: harnessAuthoritySchema,
  authoritySubsetProof: authoritySubsetProofSchema,
  signal: signalSchema,
  decision: decisionSchema,
  act: actSchema,
  verification: verificationSchema,
  harness: harnessSchema,
  harnessReceipt: harnessReceiptSchema,
  target: targetSchema,
  opportunity: opportunitySchema,
  thesisAssessment: thesisAssessmentSchema,
  selection: selectionSchema,
  skillBinding: skillBindingSchema,
  targetTransitionEntry: targetTransitionEntrySchema,
  selectionCycle: selectionCycleSchema,
  reflectionEntry: reflectionEntrySchema,
  feedEntry: feedEntrySchema,
  artifact: artifactSchema,
  redaction: redactionSchema,
  ledgerEntry: ledgerRecordSchema,
  handoffSignal: handoffSignalV1Schema,
  handoffState: handoffStateV1Schema,
  suppressionRecord: suppressionRecordV1Schema,
} as const;

export const runxAuxiliarySchemas = {
  registryBinding: registryBindingSchema,
  reviewReceiptOutput: reviewReceiptOutputSchema,
} as const;

export const runxGeneratedSchemaArtifacts = {
  "output.schema.json": outputSchema,
  "agent-context-envelope.schema.json": agentContextEnvelopeSchema,
  "agent-act-invocation.schema.json": agentActInvocationSchema,
  "question.schema.json": questionSchema,
  "approval-gate.schema.json": approvalGateSchema,
  "resolution-request.schema.json": resolutionRequestSchema,
  "resolution-response.schema.json": resolutionResponseSchema,
  "act-receipt.schema.json": actReceiptEnvelopeSchema,
  "credential-envelope.schema.json": credentialEnvelopeSchema,
  "scope-admission.schema.json": scopeAdmissionSchema,
  "authority-proof.schema.json": authorityProofSchema,
  "doctor.schema.json": doctorV1Schema,
  "dev.schema.json": devV1Schema,
  "list.schema.json": listV1Schema,
  "receipt.schema.json": receiptV1Schema,
  "fixture.schema.json": fixtureV1Schema,
  "tool-manifest.schema.json": toolManifestV1Schema,
  "packet-index.schema.json": packetIndexV1Schema,
  "act-assignment.schema.json": actAssignmentV1Schema,
  "reference.schema.json": referenceSchema,
  "authority.schema.json": harnessAuthoritySchema,
  "authority-subset-proof.schema.json": authoritySubsetProofSchema,
  "signal.schema.json": signalSchema,
  "decision.schema.json": decisionSchema,
  "act.schema.json": actSchema,
  "verification.schema.json": verificationSchema,
  "harness.schema.json": harnessSchema,
  "harness-receipt.schema.json": harnessReceiptSchema,
  "target.schema.json": targetSchema,
  "opportunity.schema.json": opportunitySchema,
  "thesis-assessment.schema.json": thesisAssessmentSchema,
  "selection.schema.json": selectionSchema,
  "skill-binding.schema.json": skillBindingSchema,
  "target-transition-entry.schema.json": targetTransitionEntrySchema,
  "selection-cycle.schema.json": selectionCycleSchema,
  "reflection-entry.schema.json": reflectionEntrySchema,
  "feed-entry.schema.json": feedEntrySchema,
  "artifact.schema.json": artifactSchema,
  "redaction.schema.json": redactionSchema,
  "ledger-entry.schema.json": ledgerRecordSchema,
  "handoff-signal.schema.json": handoffSignalV1Schema,
  "handoff-state.schema.json": handoffStateV1Schema,
  "suppression-record.schema.json": suppressionRecordV1Schema,
  "registry-binding.schema.json": registryBindingSchema,
  "review-receipt-output.schema.json": reviewReceiptOutputSchema,
} as const;

export {
  buildHostedOpenApiPublicSchemas,
} from "./openapi-public.js";
export { buildHostedOpenApiRuntimeSchemas } from "./openapi-runtime.js";
export { buildHostedOpenApiSchemas } from "./openapi.js";
