import { openApiSchemaRef } from "./openapi-refs.js";

export function buildHostedOpenApiPublicSchemas(): Readonly<Record<string, unknown>> {
  return {
    PublicSystemStatusEnvelope: {
      type: "object",
      properties: {
        overall: { type: "string" },
        checked_at: { type: "string", format: "date-time" },
        summary: { type: "string" },
        checks: {
          type: "array",
          items: {
            type: "object",
            properties: {
              id: { type: "string" },
              label: { type: "string" },
              status: { type: "string" },
              detail: { type: "string" },
            },
            required: ["id", "label", "status"],
            additionalProperties: false,
          },
        },
      },
      required: ["overall", "checked_at", "summary", "checks"],
      additionalProperties: false,
    },
    PublicIntegrationSummary: {
      type: "object",
      properties: {
        slug: { type: "string" },
        name: { type: "string" },
        description: { type: "string" },
        category: { type: "string" },
        status: { type: "string", enum: ["wired", "byo-ready", "catalog"] },
        connect_mode: { type: "string", enum: ["oauth", "byo", "none"] },
        source: { type: "string", enum: ["live", "seeded"] },
        auth_mode: { type: "string" },
        docs_url: { type: "string", format: "uri" },
        brand_color: { type: "string", pattern: "^#[A-Fa-f0-9]{6}$" },
        logo_url: { type: "string", format: "uri" },
      },
      required: ["slug", "name", "description", "category", "status", "connect_mode", "source"],
      additionalProperties: false,
    },
    PublicIntegrationListEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        as_of: { type: "string", format: "date-time" },
        source: { type: "string", enum: ["live", "seeded"] },
        total: { type: "integer" },
        integrations: {
          type: "array",
          items: openApiSchemaRef("PublicIntegrationSummary"),
        },
      },
      required: ["status", "as_of", "source", "total", "integrations"],
      additionalProperties: false,
    },
    PublicIntegrationEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        as_of: { type: "string", format: "date-time" },
        source: { type: "string", enum: ["live", "seeded"] },
        integration: openApiSchemaRef("PublicIntegrationSummary"),
      },
      required: ["status", "as_of", "source", "integration"],
      additionalProperties: false,
    },
    PublicFeedItem: {
      type: "object",
      properties: {
        id: { type: "string" },
        source: { type: "string" },
        lane: { type: "string", enum: ["runx", "aster"] },
        status: { type: "string", enum: ["success", "failure", "pending", "running", "waiting", "cancelled"] },
        title: { type: "string" },
        target: { type: "string" },
        timestamp: { type: "string", format: "date-time" },
        summary: { type: "string" },
        repo: { type: "string" },
        workflow: { type: "string" },
        branch: { type: "string" },
        commit: { type: "string" },
        run_id: { type: "string" },
        receipt_id: { type: "string" },
        skill_id: { type: "string" },
        actions_count: { type: "integer" },
        url: { type: "string", format: "uri" },
        metadata: { type: "object", additionalProperties: true },
      },
      required: ["id", "source", "lane", "status", "title", "target", "timestamp"],
      additionalProperties: false,
    },
    PublicFeedEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        as_of: { type: "string", format: "date-time" },
        feed: {
          type: "array",
          items: openApiSchemaRef("PublicFeedItem"),
        },
      },
      required: ["status", "as_of", "feed"],
      additionalProperties: false,
    },
    PublicSkillSummary: {
      type: "object",
      properties: {
        skill_id: { type: "string" },
        owner: { type: "string" },
        owner_handle: { type: "string" },
        trust_tier: { type: "string", enum: ["first_party", "verified", "community"] },
        name: { type: "string" },
        description: { type: "string" },
        catalog_kind: { type: "string", enum: ["skill", "chain"] },
        version: { type: "string" },
        created_at: { type: "string", format: "date-time" },
        updated_at: { type: "string", format: "date-time" },
        source_type: { type: "string" },
        profile_mode: { type: "string", enum: ["profiled", "portable"] },
        runner_names: { type: "array", items: { type: "string" } },
        required_scopes: { type: "array", items: { type: "string" } },
        tags: { type: "array", items: { type: "string" } },
        category: { type: "string" },
        category_label: { type: "string" },
        trust_signals: {
          type: "array",
          items: {
            $ref: "#/components/schemas/PublicTrustSignal",
          },
        },
        install_count: { type: "integer" },
        page_url: { type: "string", format: "uri" },
        install_command: { type: "string" },
        run_command: { type: "string" },
        latest_receipt: openApiSchemaRef("PublicLatestReceipt"),
      },
      required: [
        "skill_id",
        "owner",
        "owner_handle",
        "trust_tier",
        "name",
        "catalog_kind",
        "version",
        "created_at",
        "updated_at",
        "source_type",
        "profile_mode",
        "runner_names",
        "required_scopes",
        "tags",
        "category",
        "category_label",
        "trust_signals",
        "install_count",
        "page_url",
        "install_command",
        "run_command",
      ],
      additionalProperties: false,
    },
    PublicTrustSignal: {
      type: "object",
      properties: {
        id: { type: "string" },
        label: { type: "string" },
        status: { type: "string", enum: ["verified", "declared", "not_declared", "placeholder"] },
        value: { type: "string" },
      },
      required: ["id", "label", "status", "value"],
      additionalProperties: false,
    },
    PublicPublisher: {
      type: "object",
      properties: {
        id: { type: "string" },
        kind: { type: "string", enum: ["organization", "user", "team", "service", "publisher"] },
        handle: { type: "string" },
        display_name: { type: "string" },
      },
      required: ["id", "kind"],
      additionalProperties: false,
    },
    PublicAttestation: {
      type: "object",
      properties: {
        kind: { type: "string", enum: ["source", "publisher", "verification"] },
        id: { type: "string" },
        status: { type: "string", enum: ["verified", "declared"] },
        summary: { type: "string" },
        source: { type: "string", format: "uri" },
        issued_at: { type: "string", format: "date-time" },
        metadata: { type: "object", additionalProperties: true },
      },
      required: ["kind", "id", "status", "summary"],
      additionalProperties: false,
    },
    PublicLatestReceipt: {
      type: "object",
      properties: {
        receipt_id: { type: "string" },
        run_id: { type: "string" },
        created_at: { type: "string", format: "date-time" },
        status: { type: "string" },
      },
      required: ["receipt_id", "created_at", "status"],
      additionalProperties: false,
    },
    PublicFacetCount: {
      type: "object",
      properties: {
        value: { type: "string" },
        count: { type: "integer" },
      },
      required: ["value", "count"],
      additionalProperties: false,
    },
    PublicSkillListQuery: {
      type: "object",
      properties: {
        q: { type: "string" },
        owner: { type: "string" },
        tag: { type: "string" },
        kind: { type: "string", enum: ["skill", "chain"] },
        category: { type: "string" },
        source_type: { type: "string" },
        profile_mode: { type: "string", enum: ["profiled", "portable"] },
        sort: { type: "string", enum: ["newest", "a-z", "most-installed"] },
        limit: { type: "integer", minimum: 1, maximum: 100 },
      },
      required: ["q", "sort", "limit"],
      additionalProperties: false,
    },
    PublicSkillFacets: {
      type: "object",
      properties: {
        owners: { type: "array", items: openApiSchemaRef("PublicFacetCount") },
        tags: { type: "array", items: openApiSchemaRef("PublicFacetCount") },
        kinds: { type: "array", items: openApiSchemaRef("PublicFacetCount") },
        categories: { type: "array", items: openApiSchemaRef("PublicCategoryFacetCount") },
        source_types: { type: "array", items: openApiSchemaRef("PublicFacetCount") },
        profile_modes: { type: "array", items: openApiSchemaRef("PublicFacetCount") },
      },
      required: ["owners", "tags", "kinds", "categories", "source_types", "profile_modes"],
      additionalProperties: false,
    },
    PublicCategoryFacetCount: {
      type: "object",
      properties: {
        value: { type: "string" },
        label: { type: "string" },
        count: { type: "integer" },
      },
      required: ["value", "label", "count"],
      additionalProperties: false,
    },
    PublicOwnerProfileLink: {
      type: "object",
      properties: {
        label: { type: "string" },
        url: { type: "string", format: "uri" },
      },
      required: ["label", "url"],
      additionalProperties: false,
    },
    PublicOwnerProfile: {
      type: "object",
      properties: {
        owner: { type: "string" },
        handle: { type: "string" },
        display_name: { type: "string" },
        description: { type: "string" },
        website_url: { type: "string", format: "uri" },
        github_url: { type: "string", format: "uri" },
        kind: { type: "string", enum: ["org", "user", "team"] },
        verified: { type: "boolean" },
        links: { type: "array", items: openApiSchemaRef("PublicOwnerProfileLink") },
        skill_count: { type: "integer" },
        install_count: { type: "integer" },
        categories: { type: "array", items: openApiSchemaRef("PublicCategoryFacetCount") },
        updated_at: { type: "string", format: "date-time" },
      },
      required: [
        "owner",
        "handle",
        "display_name",
        "description",
        "kind",
        "verified",
        "links",
        "skill_count",
        "install_count",
        "categories",
      ],
      additionalProperties: false,
    },
    PublicOwnerProfileEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        owner: openApiSchemaRef("PublicOwnerProfile"),
        profile: openApiSchemaRef("PublicOwnerProfile"),
      },
      required: ["status"],
      additionalProperties: false,
    },
    PublicSkillListEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        query: openApiSchemaRef("PublicSkillListQuery"),
        total: { type: "integer" },
        facets: openApiSchemaRef("PublicSkillFacets"),
        skills: { type: "array", items: openApiSchemaRef("PublicSkillSummary") },
      },
      required: ["status", "query", "total", "facets", "skills"],
      additionalProperties: false,
    },
    PublicToolSearchResult: {
      type: "object",
      properties: {
        tool_id: { type: "string" },
        name: { type: "string" },
        summary: { type: "string" },
        source: { type: "string" },
        source_label: { type: "string" },
        source_type: { type: "string" },
        namespace: { type: "string" },
        external_name: { type: "string" },
        required_scopes: { type: "array", items: { type: "string" } },
        tags: { type: "array", items: { type: "string" } },
        catalog_ref: { type: "string" },
      },
      required: [
        "tool_id",
        "name",
        "source",
        "source_label",
        "source_type",
        "namespace",
        "external_name",
        "required_scopes",
        "tags",
        "catalog_ref",
      ],
      additionalProperties: false,
    },
    PublicToolListQuery: {
      type: "object",
      properties: {
        q: { type: "string" },
        source: { type: "string" },
        limit: { type: "integer", minimum: 1, maximum: 100 },
      },
      required: ["q", "source", "limit"],
      additionalProperties: false,
    },
    PublicToolListEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        query: openApiSchemaRef("PublicToolListQuery"),
        total: { type: "integer" },
        tools: { type: "array", items: openApiSchemaRef("PublicToolSearchResult") },
      },
      required: ["status", "query", "total", "tools"],
      additionalProperties: false,
    },
    PublicToolInput: {
      type: "object",
      properties: {
        type: { type: "string" },
        required: { type: "boolean" },
        description: { type: "string" },
      },
      required: ["type", "required"],
      additionalProperties: true,
    },
    PublicToolInspectProvenance: {
      type: "object",
      properties: {
        origin: { type: "string", enum: ["local", "imported"] },
        source: { type: "string" },
        source_label: { type: "string" },
        source_type: { type: "string" },
        namespace: { type: "string" },
        external_name: { type: "string" },
        catalog_ref: { type: "string" },
        tool_id: { type: "string" },
        tags: { type: "array", items: { type: "string" } },
      },
      required: ["origin"],
      additionalProperties: false,
    },
    PublicToolDetail: {
      type: "object",
      properties: {
        ref: { type: "string" },
        name: { type: "string" },
        description: { type: "string" },
        execution_source_type: { type: "string" },
        inputs: {
          type: "object",
          additionalProperties: openApiSchemaRef("PublicToolInput"),
        },
        scopes: { type: "array", items: { type: "string" } },
        mutating: { type: "boolean" },
        runtime: { type: "object", additionalProperties: true },
        risk: { type: "object", additionalProperties: true },
        runx: { type: "object", additionalProperties: true },
        reference_path: { type: "string" },
        skill_directory: { type: "string" },
        provenance: openApiSchemaRef("PublicToolInspectProvenance"),
      },
      required: [
        "ref",
        "name",
        "execution_source_type",
        "inputs",
        "scopes",
        "reference_path",
        "skill_directory",
        "provenance",
      ],
      additionalProperties: false,
    },
    PublicToolDetailEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        tool: openApiSchemaRef("PublicToolDetail"),
      },
      required: ["status", "tool"],
      additionalProperties: false,
    },
    PublicEvidenceEvent: {
      type: "object",
      properties: {
        id: { type: "string" },
        kind: {
          type: "string",
          description: "Publisher-defined evidence kind. Reserved runtime values include runx_run and harness_run.",
        },
        source: { type: "string" },
        status: { type: "string", enum: ["success", "failure", "pending", "running", "waiting", "cancelled"] },
        title: { type: "string" },
        timestamp: { type: "string", format: "date-time" },
        summary: { type: "string" },
        repo: { type: "string" },
        workflow: { type: "string" },
        branch: { type: "string" },
        commit: { type: "string" },
        skill_id: { type: "string" },
        run_id: { type: "string" },
        receipt_id: { type: "string" },
        url: { type: "string", format: "uri" },
        metadata: { type: "object", additionalProperties: true },
      },
      required: ["id", "kind", "source", "status", "title", "timestamp"],
      additionalProperties: false,
    },
    PublicHarnessDeclaredCase: {
      type: "object",
      properties: {
        name: { type: "string" },
        runner: { type: "string" },
        expected_status: { type: "string", enum: ["success", "failure", "needs_resolution", "policy_denied"] },
      },
      required: ["name"],
      additionalProperties: false,
    },
    PublicHarnessSummary: {
      type: "object",
      properties: {
        declared_case_count: { type: "integer" },
        declared_cases: { type: "array", items: openApiSchemaRef("PublicHarnessDeclaredCase") },
        latest_run: openApiSchemaRef("PublicEvidenceEvent"),
        recent_runs: { type: "array", items: openApiSchemaRef("PublicEvidenceEvent") },
      },
      required: ["declared_case_count", "declared_cases", "recent_runs"],
      additionalProperties: false,
    },
    PublicSkillDetail: {
      type: "object",
      properties: {
        skill_id: { type: "string" },
        owner: { type: "string" },
        owner_handle: { type: "string" },
        trust_tier: { type: "string", enum: ["first_party", "verified", "community"] },
        name: { type: "string" },
        description: { type: "string" },
        catalog_kind: { type: "string", enum: ["skill", "chain"] },
        version: { type: "string" },
        created_at: { type: "string", format: "date-time" },
        updated_at: { type: "string", format: "date-time" },
        source_type: { type: "string" },
        profile_mode: { type: "string", enum: ["profiled", "portable"] },
        runner_names: { type: "array", items: { type: "string" } },
        required_scopes: { type: "array", items: { type: "string" } },
        tags: { type: "array", items: { type: "string" } },
        category: { type: "string" },
        category_label: { type: "string" },
        trust_signals: { type: "array", items: openApiSchemaRef("PublicTrustSignal") },
        install_count: { type: "integer" },
        page_url: { type: "string", format: "uri" },
        install_command: { type: "string" },
        run_command: { type: "string" },
        latest_receipt: openApiSchemaRef("PublicLatestReceipt"),
        publisher: openApiSchemaRef("PublicPublisher"),
        attestations: { type: "array", items: openApiSchemaRef("PublicAttestation") },
        digest: { type: "string" },
        profile_digest: { type: "string" },
        markdown: { type: "string" },
        harness: openApiSchemaRef("PublicHarnessSummary"),
        recent_activity: { type: "array", items: openApiSchemaRef("PublicFeedItem") },
        source: openApiSchemaRef("PublicSkillSource"),
      },
      required: [
        "skill_id",
        "owner",
        "owner_handle",
        "trust_tier",
        "name",
        "catalog_kind",
        "version",
        "created_at",
        "updated_at",
        "source_type",
        "profile_mode",
        "runner_names",
        "required_scopes",
        "tags",
        "category",
        "category_label",
        "trust_signals",
        "install_count",
        "page_url",
        "install_command",
        "run_command",
        "publisher",
        "attestations",
        "digest",
        "markdown",
        "harness",
        "recent_activity",
      ],
      additionalProperties: false,
    },
    PublicSkillDetailEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        skill: openApiSchemaRef("PublicSkillDetail"),
      },
      required: ["status", "skill"],
      additionalProperties: false,
    },
    PublicSkillSource: {
      type: "object",
      properties: {
        provider: { type: "string", const: "github" },
        repo: { type: "string" },
        repo_url: { type: "string", format: "uri" },
        skill_path: { type: "string" },
        profile_path: { type: "string" },
        ref: { type: "string" },
        sha: { type: "string" },
        event: { type: "string", enum: ["enrollment", "push", "tag", "tombstone"] },
        immutable: { type: "boolean" },
        live: { type: "boolean" },
        tombstoned: { type: "boolean" },
        tag: { type: "string" },
        publisher_handle: { type: "string" },
      },
      required: ["provider", "repo", "repo_url", "skill_path", "ref", "sha", "event", "immutable", "live"],
      additionalProperties: false,
    },
    AcquireSkillRequest: {
      type: "object",
      properties: {
        installation_id: { type: "string" },
        version: { type: "string" },
        channel: { type: "string" },
      },
      required: ["installation_id"],
      additionalProperties: false,
    },
    AcquireSkillResponse: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        install_count: { type: "integer" },
        acquisition: {
          type: "object",
          properties: {
            skill_id: { type: "string" },
            owner: { type: "string" },
            name: { type: "string" },
            version: { type: "string" },
            digest: { type: "string" },
            markdown: { type: "string" },
            profile_document: { type: "string" },
            profile_digest: { type: "string" },
            trust_tier: { type: "string", enum: ["first_party", "verified", "community"] },
            publisher: openApiSchemaRef("PublicPublisher"),
            source_metadata: openApiSchemaRef("PublicSkillSource"),
            attestations: { type: "array", items: openApiSchemaRef("PublicAttestation") },
            runner_names: {
              type: "array",
              items: { type: "string" },
            },
          },
          required: [
            "skill_id",
            "owner",
            "name",
            "version",
            "digest",
            "markdown",
            "trust_tier",
            "publisher",
            "attestations",
            "runner_names",
          ],
          additionalProperties: false,
        },
      },
      required: ["status", "install_count", "acquisition"],
      additionalProperties: false,
    },
    SelfPublishRepositorySummary: {
      type: "object",
      properties: {
        full_name: { type: "string" },
        owner: { type: "string" },
        repo: { type: "string" },
        default_branch: { type: "string" },
        description: { type: "string" },
        skill_name: { type: "string" },
        has_skill_markdown: { type: "boolean" },
        has_root_profile: { type: "boolean" },
        has_fallback_profile: { type: "boolean" },
      },
      required: [
        "full_name",
        "owner",
        "repo",
        "default_branch",
        "has_skill_markdown",
        "has_root_profile",
        "has_fallback_profile",
      ],
      additionalProperties: false,
    },
    SelfPublishDraftPullRequest: {
      type: "object",
      properties: {
        id: { type: "string" },
        number: { type: "integer" },
        title: { type: "string" },
        body: { type: "string" },
        url: { type: "string", format: "uri" },
        head_ref: { type: "string" },
        state: { type: "string", enum: ["open", "merged"] },
        created_at: { type: "string", format: "date-time" },
      },
      required: ["id", "number", "title", "body", "url", "head_ref", "state", "created_at"],
      additionalProperties: false,
    },
    SelfPublishEnrollment: {
      type: "object",
      properties: {
        handle: { type: "string" },
        actor: { type: "string" },
        repo_full_name: { type: "string" },
        owner: { type: "string" },
        repo: { type: "string" },
        default_branch: { type: "string" },
        skill_name: { type: "string" },
        status: { type: "string", enum: ["waiting_for_merge", "indexed", "error", "tombstoned"] },
        source_url: { type: "string", format: "uri" },
        page_url: { type: "string", format: "uri" },
        indexed_skill_id: { type: "string" },
        active_version: { type: "string" },
        active_ref: { type: "string" },
        source_sha: { type: "string" },
        profile_path: { type: "string" },
        compatibility_fallback: { type: "boolean" },
        warnings: { type: "array", items: { type: "string" } },
        draft_pr: openApiSchemaRef("SelfPublishDraftPullRequest"),
        published_versions: { type: "array", items: { type: "string" } },
        created_at: { type: "string", format: "date-time" },
        updated_at: { type: "string", format: "date-time" },
        last_indexed_at: { type: "string", format: "date-time" },
        tombstoned_at: { type: "string", format: "date-time" },
        error: { type: "string" },
      },
      required: [
        "handle",
        "actor",
        "repo_full_name",
        "owner",
        "repo",
        "default_branch",
        "status",
        "source_url",
        "compatibility_fallback",
        "warnings",
        "published_versions",
        "created_at",
        "updated_at",
      ],
      additionalProperties: false,
    },
    SelfPublishRepoListEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        repos: { type: "array", items: openApiSchemaRef("SelfPublishRepositorySummary") },
      },
      required: ["status", "repos"],
      additionalProperties: false,
    },
    SelfPublishEnrollmentRequest: {
      type: "object",
      properties: {
        actor: { type: "string" },
        repo_full_name: { type: "string" },
      },
      required: ["actor", "repo_full_name"],
      additionalProperties: false,
    },
    SelfPublishEnrollmentEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        enrollment: openApiSchemaRef("SelfPublishEnrollment"),
      },
      required: ["status", "enrollment"],
      additionalProperties: false,
    },
    SelfPublishWebhookRequest: {
      type: "object",
      properties: {
        type: { type: "string", enum: ["push", "tag", "repository.deleted"] },
        repo_full_name: { type: "string" },
        ref: { type: "string" },
        tag: { type: "string" },
      },
      required: ["type", "repo_full_name"],
      additionalProperties: false,
    },
    SelfPublishWebhookEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "accepted" },
        updated: { type: "integer" },
        enrollments: { type: "array", items: openApiSchemaRef("SelfPublishEnrollment") },
      },
      required: ["status", "updated", "enrollments"],
      additionalProperties: false,
    },
    PublicHarnessEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        skill_id: { type: "string" },
        harness: openApiSchemaRef("PublicHarnessSummary"),
      },
      required: ["status", "skill_id", "harness"],
      additionalProperties: false,
    },
    PublicEvidenceEventInput: {
      type: "object",
      properties: {
        id: { type: "string" },
        kind: {
          type: "string",
          description: "Publisher-defined evidence kind. Reserved runtime values include runx_run and harness_run.",
        },
        source: { type: "string" },
        status: { type: "string", enum: ["success", "failure", "pending", "running", "waiting", "cancelled"] },
        title: { type: "string" },
        timestamp: { type: "string", format: "date-time" },
        summary: { type: "string" },
        repo: { type: "string" },
        workflow: { type: "string" },
        branch: { type: "string" },
        commit: { type: "string" },
        skill_id: { type: "string" },
        run_id: { type: "string" },
        receipt_id: { type: "string" },
        url: { type: "string", format: "uri" },
        metadata: { type: "object", additionalProperties: true },
      },
      required: ["kind", "source", "status", "title", "timestamp"],
      additionalProperties: false,
    },
    PublicEvidenceIngestRequest: {
      type: "object",
      properties: {
        events: {
          type: "array",
          items: openApiSchemaRef("PublicEvidenceEventInput"),
        },
      },
      required: ["events"],
      additionalProperties: false,
    },
    PublicEvidenceIngestEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "accepted" },
        count: { type: "integer" },
        events: {
          type: "array",
          items: openApiSchemaRef("PublicEvidenceEventInput"),
        },
      },
      required: ["status", "count", "events"],
      additionalProperties: false,
    },
    HarnessPublishSummary: {
      type: "object",
      properties: {
        status: { type: "string", enum: ["passed", "failed", "not_declared"] },
        case_count: { type: "integer" },
        assertion_error_count: { type: "integer" },
        assertion_errors: { type: "array", items: { type: "string" } },
        case_names: { type: "array", items: { type: "string" } },
        receipt_ids: { type: "array", items: { type: "string" } },
      },
      required: ["status", "case_count", "assertion_error_count", "assertion_errors", "case_names", "receipt_ids"],
      additionalProperties: false,
    },
    AdminRegistryPublishRequest: {
      type: "object",
      properties: {
        owner: { type: "string" },
        version: { type: "string" },
        created_at: { type: "string", format: "date-time" },
        markdown: { type: "string" },
        profile_document: { type: "string" },
        harness: openApiSchemaRef("HarnessPublishSummary"),
      },
      required: ["owner", "markdown", "harness"],
      additionalProperties: false,
    },
    AdminOwnerProfileRequest: {
      type: "object",
      properties: {
        handle: { type: "string" },
        display_name: { type: "string" },
        description: { type: "string" },
        website_url: { type: "string", format: "uri" },
        github_url: { type: "string", format: "uri" },
        kind: { type: "string", enum: ["org", "user", "team"] },
        verified: { type: "boolean" },
        links: { type: "array", items: openApiSchemaRef("PublicOwnerProfileLink") },
      },
      additionalProperties: false,
    },
    AdminRegistryPublishEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        publish: {
          type: "object",
          additionalProperties: true,
        },
        harness: openApiSchemaRef("HarnessPublishSummary"),
      },
      required: ["status", "publish", "harness"],
      additionalProperties: false,
    },
  } as const;
}
