import { openApiSchemaRef, protocolArtifactRef } from "./openapi-refs.js";

export function buildHostedOpenApiRuntimeSchemas(): Readonly<Record<string, unknown>> {
  const envelope = {
    type: "object",
    additionalProperties: true,
  };
  return {
    StatusEnvelope: {
      type: "object",
      additionalProperties: true,
      properties: {
        status: { type: "string" },
      },
      required: ["status"],
    },
    ErrorEnvelope: {
      type: "object",
      properties: {
        error: { type: "string" },
        status: { type: "string" },
      },
      required: ["error"],
      additionalProperties: true,
    },
    PrincipalSummary: {
      type: "object",
      properties: {
        principal_id: { type: "string" },
        role: { type: "string", enum: ["user", "admin", "service"] },
        display_name: { type: "string" },
        scopes: {
          type: "array",
          items: { type: "string" },
        },
        namespace_prefixes: {
          type: "array",
          items: { type: "string" },
        },
      },
      required: ["principal_id", "role"],
      additionalProperties: false,
    },
    PrincipalEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        principal: openApiSchemaRef("PrincipalSummary"),
      },
      required: ["status", "principal"],
      additionalProperties: false,
    },
    AgentConfigSummary: {
      oneOf: [
        {
          type: "object",
          properties: {
            provider: { type: "string" },
            model: { type: "string" },
            base_url: { type: "string", format: "uri" },
            has_api_key: { type: "boolean", const: true },
            created_at: { type: "string", format: "date-time" },
            updated_at: { type: "string", format: "date-time" },
          },
          required: ["provider", "model", "has_api_key", "created_at", "updated_at"],
          additionalProperties: false,
        },
        { type: "null" },
      ],
    },
    AgentConfigEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        agent_config: openApiSchemaRef("AgentConfigSummary"),
      },
      required: ["status", "agent_config"],
      additionalProperties: false,
    },
    ServiceTokenExchangeEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        access_token: { type: "string" },
        expires_at: { type: "string", format: "date-time" },
        principal: openApiSchemaRef("PrincipalSummary"),
      },
      required: ["status", "access_token", "expires_at", "principal"],
      additionalProperties: false,
    },
    KnowledgeNamespaceSummary: {
      type: "object",
      properties: {
        id: { type: "string" },
        namespace: { type: "string" },
        title: { type: "string" },
        description: { type: "string" },
        metadata: { type: "object", additionalProperties: true },
        created_at: { type: "string", format: "date-time" },
        updated_at: { type: "string", format: "date-time" },
      },
      required: ["id", "namespace", "metadata", "created_at", "updated_at"],
      additionalProperties: false,
    },
    KnowledgeNamespaceEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        namespace: openApiSchemaRef("KnowledgeNamespaceSummary"),
      },
      required: ["status", "namespace"],
      additionalProperties: false,
    },
    KnowledgeNamespaceListEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        namespaces: {
          type: "array",
          items: openApiSchemaRef("KnowledgeNamespaceSummary"),
        },
      },
      required: ["status", "namespaces"],
      additionalProperties: false,
    },
    KnowledgeSubjectSummary: {
      type: "object",
      properties: {
        id: { type: "string" },
        namespace: { type: "string" },
        subject_locator: { type: "string" },
        subject_kind: { type: "string" },
        subject_facet: { type: "string" },
        title: { type: "string" },
        canonical_uri: { type: "string" },
        aliases: { type: "array", items: { type: "string" } },
        metadata: { type: "object", additionalProperties: true },
        created_at: { type: "string", format: "date-time" },
        updated_at: { type: "string", format: "date-time" },
      },
      required: ["id", "namespace", "subject_locator", "subject_kind", "aliases", "metadata", "created_at", "updated_at"],
      additionalProperties: false,
    },
    KnowledgeSubjectEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        subject: openApiSchemaRef("KnowledgeSubjectSummary"),
      },
      required: ["status", "subject"],
      additionalProperties: false,
    },
    KnowledgeEntrySummary: {
      type: "object",
      properties: {
        id: { type: "string" },
        namespace: { type: "string" },
        subject_locator: { type: "string" },
        entry_kind: { type: "string" },
        author_id: { type: "string" },
        author_role: { type: "string", enum: ["user", "admin", "service"] },
        confidence: { type: "number" },
        freshness: { type: "string" },
        idempotency_key: { type: "string" },
        content: {},
        metadata: { type: "object", additionalProperties: true },
        provenance: { type: "object", additionalProperties: true },
        recorded_at: { type: "string", format: "date-time" },
        created_at: { type: "string", format: "date-time" },
      },
      required: [
        "id",
        "namespace",
        "subject_locator",
        "entry_kind",
        "author_id",
        "author_role",
        "content",
        "metadata",
        "provenance",
        "recorded_at",
        "created_at",
      ],
      additionalProperties: false,
    },
    KnowledgeEntryEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", enum: ["success", "accepted"] },
        entry: openApiSchemaRef("KnowledgeEntrySummary"),
      },
      required: ["status", "entry"],
      additionalProperties: false,
    },
    KnowledgeEntryListEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        entries: {
          type: "array",
          items: openApiSchemaRef("KnowledgeEntrySummary"),
        },
      },
      required: ["status", "entries"],
      additionalProperties: false,
    },
    KnowledgeLinkSummary: {
      type: "object",
      properties: {
        id: { type: "string" },
        namespace: { type: "string" },
        source_subject_locator: { type: "string" },
        target_subject_locator: { type: "string" },
        link_kind: { type: "string" },
        author_id: { type: "string" },
        author_role: { type: "string", enum: ["user", "admin", "service"] },
        confidence: { type: "number" },
        provenance: { type: "object", additionalProperties: true },
        metadata: { type: "object", additionalProperties: true },
        created_at: { type: "string", format: "date-time" },
      },
      required: [
        "id",
        "namespace",
        "source_subject_locator",
        "target_subject_locator",
        "link_kind",
        "author_id",
        "author_role",
        "provenance",
        "metadata",
        "created_at",
      ],
      additionalProperties: false,
    },
    KnowledgeLinkEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", enum: ["success", "accepted"] },
        link: openApiSchemaRef("KnowledgeLinkSummary"),
      },
      required: ["status", "link"],
      additionalProperties: false,
    },
    KnowledgeLinkListEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        links: {
          type: "array",
          items: openApiSchemaRef("KnowledgeLinkSummary"),
        },
      },
      required: ["status", "links"],
      additionalProperties: false,
    },
    KnowledgeSnapshotSummary: {
      type: "object",
      properties: {
        id: { type: "string" },
        namespace: { type: "string" },
        subject_locator: { type: "string" },
        snapshot_name: { type: "string" },
        body: {},
        source_refs: { type: "array", items: { type: "object", additionalProperties: true } },
        projector_id: { type: "string" },
        watermark: { type: "string" },
        metadata: { type: "object", additionalProperties: true },
        visibility: { type: "string", enum: ["private", "published"] },
        created_at: { type: "string", format: "date-time" },
        updated_at: { type: "string", format: "date-time" },
        published_at: { type: "string", format: "date-time" },
      },
      required: ["id", "namespace", "snapshot_name", "body", "source_refs", "metadata", "visibility", "created_at", "updated_at"],
      additionalProperties: false,
    },
    KnowledgeSnapshotEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        snapshot: openApiSchemaRef("KnowledgeSnapshotSummary"),
      },
      required: ["status", "snapshot"],
      additionalProperties: false,
    },
    DeletedEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "deleted" },
      },
      required: ["status"],
      additionalProperties: false,
    },
    HostedRunSummary: protocolArtifactRef("hosted/hosted-run-summary.schema.json"),
    CreateRunRequest: protocolArtifactRef("hosted/create-run.request.schema.json"),
    PutAgentConfigRequest: protocolArtifactRef("hosted/agent-config.request.schema.json"),
    ServiceTokenExchangeRequest: protocolArtifactRef("hosted/service-token-exchange.request.schema.json"),
    PutKnowledgeNamespaceRequest: {
      type: "object",
      properties: {
        title: { type: "string" },
        description: { type: "string" },
        metadata: { type: "object", additionalProperties: true },
      },
      additionalProperties: false,
    },
    PutKnowledgeSubjectRequest: {
      type: "object",
      properties: {
        subject_kind: { type: "string" },
        subject_facet: { type: "string" },
        title: { type: "string" },
        canonical_uri: { type: "string" },
        aliases: { type: "array", items: { type: "string" } },
        metadata: { type: "object", additionalProperties: true },
      },
      required: ["subject_kind"],
      additionalProperties: false,
    },
    AppendKnowledgeEntryRequest: {
      type: "object",
      properties: {
        entry_kind: { type: "string" },
        content: {},
        confidence: { type: "number" },
        freshness: { type: "string" },
        idempotency_key: { type: "string" },
        metadata: { type: "object", additionalProperties: true },
        provenance: { type: "object", additionalProperties: true },
        recorded_at: { type: "string", format: "date-time" },
        created_at: { type: "string", format: "date-time" },
      },
      required: ["entry_kind", "content"],
      additionalProperties: false,
    },
    AppendKnowledgeLinkRequest: {
      type: "object",
      properties: {
        link_kind: { type: "string" },
        target_subject_locator: { type: "string" },
        confidence: { type: "number" },
        provenance: { type: "object", additionalProperties: true },
        metadata: { type: "object", additionalProperties: true },
        created_at: { type: "string", format: "date-time" },
      },
      required: ["link_kind", "target_subject_locator"],
      additionalProperties: false,
    },
    PutKnowledgeSnapshotRequest: {
      type: "object",
      properties: {
        subject_locator: { type: "string" },
        body: {},
        source_refs: { type: "array", items: { type: "object", additionalProperties: true } },
        projector_id: { type: "string" },
        watermark: { type: "string" },
        metadata: { type: "object", additionalProperties: true },
        visibility: { type: "string", enum: ["private", "published"] },
        created_at: { type: "string", format: "date-time" },
        updated_at: { type: "string", format: "date-time" },
        published_at: { type: "string", format: "date-time" },
      },
      required: ["body"],
      additionalProperties: false,
    },
    CreateRunResponse: protocolArtifactRef("hosted/create-run.response.schema.json"),
    RunListEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        runs: {
          type: "array",
          items: openApiSchemaRef("HostedRunSummary"),
        },
      },
      required: ["status", "runs"],
      additionalProperties: false,
    },
    RunDetailEnvelope: protocolArtifactRef("hosted/hosted-run-detail.schema.json"),
    RunRequestSummary: protocolArtifactRef("hosted/run-request-summary.schema.json"),
    RunRequestsEnvelope: protocolArtifactRef("hosted/run-requests.response.schema.json"),
    RunRequestResponseRequest: protocolArtifactRef("hosted/run-request-response.request.schema.json"),
    RunResolveLegacyRequest: {
      type: "object",
      properties: {
        request_id: { type: "string" },
        payload: {},
      },
      required: ["request_id"],
      additionalProperties: false,
    },
    RunApproveLegacyRequest: {
      type: "object",
      properties: {
        request_id: { type: "string" },
        approved: { type: "boolean" },
      },
      additionalProperties: false,
    },
    RunRecordedEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "recorded" },
        run: openApiSchemaRef("HostedRunSummary"),
      },
      required: ["status", "run"],
      additionalProperties: false,
    },
    RunApprovalEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "recorded" },
        approved: { type: "boolean" },
        run: openApiSchemaRef("HostedRunSummary"),
      },
      required: ["status", "approved", "run"],
      additionalProperties: false,
    },
    ConnectTicketEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        connect: { type: "object", additionalProperties: true },
      },
      required: ["status", "connect"],
      additionalProperties: false,
    },
    CreateConnectTicketRequest: {
      type: "object",
      properties: {
        provider: { type: "string" },
        scopes: { type: "array", items: { type: "string" } },
        scope_family: { type: "string" },
        authority_kind: { type: "string", enum: ["read_only", "constructive", "destructive"] },
        target_repo: { type: "string", pattern: "^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$" },
        target_locator: { type: "string" },
        return_to: { type: "string", format: "uri" },
      },
      required: ["provider", "return_to"],
      additionalProperties: false,
    },
    HostedConnection: {
      type: "object",
      properties: {
        id: { type: "string" },
        principal_id: { type: "string" },
        provider: { type: "string" },
        scopes: { type: "array", items: { type: "string" } },
        status: { type: "string", enum: ["active", "revoked"] },
        created_at: { type: "string", format: "date-time" },
      },
      required: ["id", "principal_id", "provider", "scopes", "status", "created_at"],
      additionalProperties: false,
    },
    ConnectionListEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        connections: { type: "array", items: openApiSchemaRef("HostedConnection") },
      },
      required: ["status", "connections"],
      additionalProperties: false,
    },
    ConnectionRevokedEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "revoked" },
        connection: openApiSchemaRef("HostedConnection"),
      },
      required: ["status", "connection"],
      additionalProperties: false,
    },
    ConnectGrant: {
      type: "object",
      properties: {
        grant_id: { type: "string" },
        principal_id: { type: "string" },
        provider: { type: "string" },
        scopes: { type: "array", items: { type: "string" } },
        scope_family: { type: "string" },
        authority_kind: { type: "string", enum: ["read_only", "constructive", "destructive"] },
        target_repo: { type: "string", pattern: "^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$" },
        target_locator: { type: "string" },
        connection_id: { type: "string" },
        status: { type: "string", enum: ["active", "revoked"] },
        created_at: { type: "string", format: "date-time" },
      },
      required: ["grant_id", "principal_id", "provider", "scopes", "connection_id", "status", "created_at"],
      additionalProperties: false,
    },
    GrantListEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "success" },
        grants: { type: "array", items: openApiSchemaRef("ConnectGrant") },
      },
      required: ["status", "grants"],
      additionalProperties: false,
    },
    GrantRevokedEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "revoked" },
        grant: openApiSchemaRef("ConnectGrant"),
      },
      required: ["status", "grant"],
      additionalProperties: false,
    },
    CreateConnectSessionRequest: {
      type: "object",
      properties: {
        provider: { type: "string" },
        scopes: { type: "array", items: { type: "string" } },
        scope_family: { type: "string" },
        authority_kind: { type: "string", enum: ["read_only", "constructive", "destructive"] },
        target_repo: { type: "string", pattern: "^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$" },
        target_locator: { type: "string" },
      },
      required: ["provider"],
      additionalProperties: false,
    },
    ConnectSessionPendingEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "oauth_required" },
        session_id: { type: "string" },
        flow_id: { type: "string" },
        authorize_url: { type: "string", format: "uri" },
        poll_after_ms: { type: "integer" },
        expires_at: { type: "string", format: "date-time" },
      },
      required: ["status", "session_id", "flow_id", "authorize_url", "poll_after_ms"],
      additionalProperties: false,
    },
    ConnectSessionCompleteEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", enum: ["created", "unchanged"] },
        session_id: { type: "string" },
        flow_id: { type: "string" },
        grant: openApiSchemaRef("ConnectGrant"),
      },
      required: ["status", "grant"],
      additionalProperties: false,
    },
    ConnectSessionUnavailableEnvelope: {
      type: "object",
      properties: {
        status: { type: "string", const: "connect_unavailable" },
        provider: { type: "string" },
        provider_status: { type: "string", enum: ["wired", "byo-ready", "catalog"] },
        connect_mode: { type: "string", enum: ["oauth", "byo", "none"] },
        error: { type: "string" },
      },
      required: ["status", "provider", "provider_status", "connect_mode", "error"],
      additionalProperties: false,
    },
    ConnectSessionStatusEnvelope: {
      oneOf: [
        {
          type: "object",
          properties: {
            status: { type: "string", const: "pending" },
            session_id: { type: "string" },
            flow_id: { type: "string" },
            poll_after_ms: { type: "integer" },
          },
          required: ["status", "session_id", "flow_id", "poll_after_ms"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            status: { type: "string", const: "failed" },
            session_id: { type: "string" },
            flow_id: { type: "string" },
            error: { type: "string" },
          },
          required: ["status", "session_id", "flow_id", "error"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            status: { type: "string", enum: ["created", "unchanged"] },
            session_id: { type: "string" },
            flow_id: { type: "string" },
            grant: openApiSchemaRef("ConnectGrant"),
          },
          required: ["status", "session_id", "flow_id", "grant"],
          additionalProperties: false,
        },
      ],
    },
    GenericEnvelope: envelope,
  } as const;
}
